### ISSUE TITLE
Build an archive of each How-To and send it to S3

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-how-to#3]
We need to export each How-To in an independent archive to allow users to download the whole code before starting the How-To.  

We can use Travis to build a `.tar.gz` file for each How-To and then send it to S3.

**Comment by Njuelle** [comment]
Issue moved to [kuzzleio/kuzzle-backlog #249](https://github.com/kuzzleio/kuzzle-backlog/issues/249) via [**ZenHub**](https://www.zenhub.com/)
